apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupwork #choose your own name
  labels:
    app: groupwork
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groupwork
  template:
    metadata:
      labels:
        app: groupwork
    spec:
      containers:
      - name: groupwork
        image: tripplexx/groupwork #Change to your own here
        ports:
        - containerPort: 8000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podI